name: A basic workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    setps:
      - uses: actions/checkout@v3
      - name: run a one-ine script
        run: echo Hello, world!
      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          